name: CI

on:
  - push
  - pull_request

jobs:
  Ameba:
    runs-on: ubuntu-latest
    container:
      image: robnomad/crystal:dev-node-hoard
    steps:
      - uses: actions/checkout@v4

      - name: Format
        run: crystal tool format --check

      - name: Install shards
        run: shards install

      - name: Run ameba linter
        run: ./bin/ameba

  Tests:
    runs-on: ubuntu-latest
    container:
      image: robnomad/crystal:dev-node-hoard
    steps:
      - uses: actions/checkout@v4

      - name: Install shards
        run: shards install

      - name: Run tests
        run: |
          # Run unit tests only - skip integration tests that require auth
          crystal spec spec/auth_handler_spec.cr spec/slack_spec.cr spec/ui/
